### ISSUE TITLE
access() does resolve promise

### ISSUE THREAD

**Issue by ghost** [Globik/await-fs#1]
When calling the access() wrapper, the promise resolve callback is never called and hence, the await call waits forever. The reason is because you are checking the second callback parameter 'd' in your code. The fs.access() function however only calls the callback with one parameter, the error parameter. Therefore, d is undefined and res is never called.

**Comment by Globik** [comment]
Yes, thanx for report. I should to write something like 
if d is undefined , resolve(' ok , you can write or read the provided by path file/directory ')
So long I'd like to rewrite this module, but having no time.
In nodejs utils module there is native promisifying method. People can themselfes write a wrapper for any fs function. It's easy. No need any more in this module.
Just like in docs
https://nodejs.org/dist/latest-v9.x/docs/api/util.html#util_util_promisify_original

**Comment by Globik** [comment]
Yes I should remove if statement for 'd' parameter. It would by default resolving success if no error. Then in a user code a developer have to check the value. If result undefined, all is ok for file access.

**Comment by JGJP** [comment]
Any resolution on this? This code is also not working for other methods like unlink and writeFile. You can just do it with promisify and it will work.
